### PR TITLE
Add USM Pokemon

### PR DESCRIPTION
**Pull request by KrisXV**

### CODE REVIEW

**Comment by felixphew** [comment]
Thanks for this @KrisOnline - do you know whether the images are live on Global Link yet?

**Comment by felixphew** [comment]
OK, so I just checked and all but Zeraora are there.

**Comment by felixphew** [comment]
The Z-crystals are all there too, and the art is kind of funky - different from the old ones.

**Comment by felixphew** [comment]
I've made a [demo paste](https://pokepast.es/eed95049f5317ece).

I'll go and add types for the Z-crystals later - as well as fix the Kommo-o bug I just noticed.

**Comment by KrisXV** [comment]
oh i didnt get these alerts

**Pull request merged**
