### PR TITLE
Update Items

### PR DESCRIPTION
**Pull request by AuraStormLucario**
Add typing to some type related items; fix typos (and potentially alphabetical issues)

### CODE REVIEW

**Comment by AuraStormLucario** [comment]
This should be ready to merge whenever possible.

**Comment by felixphew** [comment]
Sorry about the delay - can we maybe leave the not-obviously-type-associated items (like Absorb Bulb and mega stones) and just do the obvious ones?

**Comment by AuraStormLucario** [comment]
I totally missed this, I'm sorry.  I don't recall associating types with megastones, but I can go ahead and remove them from the incenses and absorb bulb / luminous moss

**Comment by AuraStormLucario** [comment]
Should this be fine?

**Comment by felixphew** [comment]
It's still got the Absorb Bulb, etc. in it. If you remove them I'll merge it.

**Comment by AuraStormLucario** [comment]
All set

**Comment by felixphew** [comment]
Thanks! I'll test this and push it live some time in the next couple of hours.

**Pull request merged**
